Repository PT-Akar-Inti-Teknologi/ait_spring_boot_template, pull requests merged in 2024-09, with the labels that each got.

#26 docs: add documentation
  src/main/java/org/ait/project/guideline/example/modules/banner/service/core/impl/BannerCoreImpl.java
Labels: documentation, Review effort [1-5]: 2

#27 fix: doubled link on thumbnail and get image
  src/main/java/org/ait/project/guideline/example/modules/banner/service/core/impl/BannerCoreImpl.java
Labels: enhancement, Review effort [1-5]: 3

#28 fix: url redirecting for download image
  src/main/java/org/ait/project/guideline/example/modules/banner/service/core/impl/BannerCoreImpl.java
  src/main/java/org/ait/project/guideline/example/shared/utils/UrlBuilderUtils.java
Labels: enhancement, Review effort [1-5]: 2

#29 ci: fix cicd --run-build
  ..Jenkinsfile
  .Jenkinsfile
Labels: enhancement, Review effort [1-5]: 4
